package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"go/ast"
	"go/build"
	"go/parser"
	"go/token"

	"golang.org/x/tools/go/types"

	_ "golang.org/x/tools/go/gcimporter"
)

var (
	kitCommentPrefix = "//kit:"
	kitCommentSep    = regexp.MustCompile(`\s+`)
)

// File holds a single parsed file and associated data.
type File struct {
	pkg  *Package  // Package to which this file belongs.
	file *ast.File // Parsed AST.
}

type Package struct {
	dir      string
	name     string
	defs     map[*ast.Ident]types.Object
	files    []*File
	typesPkg *types.Package
}

// check type-checks the package. The package must be OK to proceed.
func (pkg *Package) check(fs *token.FileSet, astFiles []*ast.File) error {
	pkg.defs = make(map[*ast.Ident]types.Object)
	config := types.Config{FakeImportC: true}
	info := &types.Info{
		Defs: pkg.defs,
	}
	if typesPkg, err := config.Check(pkg.dir, fs, astFiles, info); err != nil {
		return fmt.Errorf("invalid package: %s", err)
	} else {
		pkg.typesPkg = typesPkg
		return nil
	}
}

type Generator struct {
	dir string
	pkg *Package // Package we are scanning.
}

func (g *Generator) parse(args []string) error {
	if len(args) == 1 && isDirectory(args[0]) {
		g.dir = args[0]
		return g.parsePackageDir(args[0])
	} else {
		g.dir = filepath.Dir(args[0])
		return g.parsePackageFiles(args)
	}
}

// parsePackageDir parses the package residing in the directory.
func (g *Generator) parsePackageDir(dir string) error {
	pkg, err := build.Default.ImportDir(dir, 0)
	if err != nil {
		log.Fatalf("cannot process directory %s: %s", dir, err)
	}
	var names []string
	names = append(names, pkg.GoFiles...)
	names = append(names, pkg.CgoFiles...)
	// TODO: Need to think about constants in test files. Maybe write type_string_test.go
	// in a separate pass? For later.
	// names = append(names, pkg.TestGoFiles...) // These are also in the "foo" package.
	names = append(names, pkg.SFiles...)
	names = prefixDirectory(dir, names)
	return g.parsePackage(dir, names, nil)
}

// prefixDirectory places the directory name on the beginning of each name in the list.
func prefixDirectory(directory string, names []string) []string {
	if directory == "." {
		return names
	}
	ret := make([]string, len(names))
	for i, name := range names {
		ret[i] = filepath.Join(directory, name)
	}
	return ret
}

// parsePackageFiles parses the package occupying the named files.
func (g *Generator) parsePackageFiles(names []string) error {
	return g.parsePackage(".", names, nil)
}

// parsePackage analyzes the single package constructed from the named files.
// If text is non-nil, it is a string to be used instead of the content of the file,
// to be used for testing. parsePackage exits if there is an error.
func (g *Generator) parsePackage(dir string, names []string, text interface{}) error {
	var files []*File
	var astFiles []*ast.File
	g.pkg = new(Package)
	fs := token.NewFileSet()
	for _, name := range names {
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		if parsedFile, err := parser.ParseFile(fs, name, text, parser.AllErrors|parser.ParseComments); err != nil {
			return nil
		} else {
			astFiles = append(astFiles, parsedFile)
			files = append(files, &File{
				file: parsedFile,
				pkg:  g.pkg,
			})
		}
	}
	if len(astFiles) == 0 {
		return fmt.Errorf("%s: no buildable Go files", dir)
	}
	g.pkg.name = astFiles[0].Name.Name
	g.pkg.files = files
	g.pkg.dir = dir

	// Type check the package.
	return g.pkg.check(fs, astFiles)
}

func (g *Generator) generateHeader(r *Render) {
	// Print the header and package clause.
	r.Printf("// generated by `%s %s`; DO NOT EDIT\n", appName, strings.Join(os.Args[1:], " "))
	r.Printf("package %s", g.pkg.name)
	r.Printf("\n")
	r.Printf("import \"fmt\"\n") // Used by all methods.
}

// generate produces the String method for the named type.
func (g *Generator) generateType(typeName string, render *Render) {
	typeRender := &TypeRender{name: typeName}

	for _, file := range g.pkg.files {
		if file.file != nil {
			ast.Inspect(file.file, typeRender.visit)
		}
	}

	render.Append(typeRender.render())
}
